---
title: "CO2 Levels"
author: "Alex Kuai"
date: "2022-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(plotly)
```


```{r}
data <- read_excel(path = "HiMCMData.xlsx", sheet = "CO2 Data Set 1")

df <- data.frame(Year = data $ Year,
                 CO2 = c(data $ `10 Year Average`, data $ `Annual Increase`),
                 Graphs = c(rep("10 Year Average(PPM)", nrow(data)),
                           rep("Annual Increase(PPM)", nrow(data)))) |> 
  drop_na() 
df

highlight <- df |> 
  filter(Year == 2004 & Graphs == "Annual Increase(PPM)")

highlight2 <- data |> 
  filter(Year == 2004)
highlight2
```


```{r}

ggplot(df, aes(x = Year, y = CO2, col = Graphs)) +
  geom_line() +
  geom_point() +
  geom_point(data = highlight,
             aes(x = Year, y = CO2),
             color = 'black',
             size = 3)
  labs(title = "CO2 Levels in the US from 1959 to 2021", 
      yaxis = "Carbon Dioxide in Parts Per Million (PPM)",
      caption = "HiMCM Data")


```
```{r}
data |> 
  select(Year, `Annual Increase`, `10 Year Average`) |> 
  drop_na() |> 
  ggplot(aes(x = `Annual Increase`, y = `10 Year Average` * 10)) +
  geom_point() +
  geom_point(data = highlight2,
             aes(x = `Annual Increase`, y = `10 Year Average` * 10),
             color = 'blue',
             size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(y = "10 Year Increase")
  
```

